SELECT
    A.CHAVE_LOJA,
    B.NOME_LOJA,
    B.CD_MUNIC,
    B.COD_AG_LOJA AS COD_AG,
    B.NOME_AG,
    C.LATITUDE,
    C.LONGITUDE,
    D.CHAVE_SUPERVISAO
FROM DATAWAREHOUSE.dbo.TB_INDICADORES_BE A
LEFT JOIN DATALAKE.dbo.DL_BRADESCO_EXPRESSO B
    ON A.CHAVE_LOJA = B.CHAVE_LOJA
LEFT JOIN TESTE.dbo.TB_COORD_BE_IGOR C
    ON A.CHAVE_LOJA = C.CHAVE_LOJA
LEFT JOIN MESU.dbo.CONS_DISTRIBUICAO_ENTIDADES D
    ON B.COD_AG_LOJA = D.COD_AG
WHERE A.PERIODO = :periodo
  AND A.QTD_ATIVOS > 0
  AND (
      B.COD_EMPRESA NOT IN ('29000','29001','29002','29003','97463','32399','28077','257956')
      OR B.COD_EMPRESA IS NULL
  )
  AND B.TIPO_POSTO IN ('Tradicional','Ilhas')
  AND C.LATITUDE IS NOT NULL
  AND C.LONGITUDE IS NOT NULL
  AND D.CHAVE_SUPERVISAO IS NOT NULL
