WITH POPULACAO_ATUAL AS (
    SELECT
        COD_UN_REG,
        POPULACAO,
        DATA_CENSO,
        ROW_NUMBER() OVER (
            PARTITION BY COD_UN_REG
            ORDER BY DATA_CENSO DESC
        ) AS ORDEM
    FROM IBGE.dbo.IBGE_POP
    WHERE COD_UN_REG IS NOT NULL
)
SELECT COD_UN_REG, POPULACAO, DATA_CENSO
FROM POPULACAO_ATUAL
WHERE ORDEM = 1
